# AUTOGENERATED FILE
FROM #{FROM}

#{LABEL}

#{QEMU}

ENV NODE_VERSION #{NODE_VERSION}

# Install dependencies
RUN apk add --no-cache libgcc libstdc++

RUN buildDeps='curl ca-certificates tar binutils' \
	&& set -x \
	&& apk add --no-cache $buildDeps \
	&& curl -SLO "#{BINARY_URL}" \
	&& echo "#{CHECKSUM}" | sha256sum -c - \
	&& tar -xzf "node-v$NODE_VERSION-linux-#{TARGET_ARCH}.tar.gz" -C /usr/local --strip-components=1 \
	&& rm "node-v$NODE_VERSION-linux-#{TARGET_ARCH}.tar.gz" \
	&& strip --strip-unneeded /usr/local/bin/node \
	&& apk del $buildDeps \
	&& npm config set unsafe-perm true -g --unsafe-perm \
	&& rm -rf /tmp/*

CMD ["echo","'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: http://docs.resin.io/#/pages/using/dockerfile.md"]
